export const MENSAJE_EXITOSO = "MENSAJE_EXITOSO";
export const MENSAJE_FALLIDO = "MENSAJE_FALLIDO";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const LOGIN_EXITO = "LOGIN_EXITO";

export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";

export const CERRAR_SESION = "CERRAR_SESION";

export const SUBIR_ARCHIVO = "SUBIR_ARCHIVO";

export const SUBIR_ARCHIVO_EXITO = "SUBIR_ARCHIVO_EXITO";

export const CREAR_ENLACE_EXITO = "CREAR_ENLACE_EXITO";

export const LIMPIAR_STATE = "LIMPIAR_STATE";

export const AGREGAR_PASSWORD = "AGREGAR_PASSWORD";
export const AGREGAR_DESCARGAS = "AGREGAR_DESCARGAS";

export const MOSTRAR_CARGANDO = "MOSTRAR_CARGANDO";
export const OCULTAR_CARGANDO = "OCULTAR_CARGANDO";
