export const MENSAJE_EXITOSO = "MENSAJE_EXITOSO";
export const MENSAJE_FALLIDO = "MENSAJE_FALLIDO";
export const LIMPIAR_ALERTA = "LIMPIAR_ALERTA";

export const LOGIN_EXITO = "LOGIN_EXITO";

export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";

export const CERRAR_SESION = "CERRAR_SESION";
